package main

import (
	"html/template"
	"net/http"

	"bosstransfer/internal/websession"
)

func managerLoginPageHandler(auth *websession.Auth) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/login" {
			http.NotFound(w, r)
			return
		}
		if principal, err := auth.Principal(r); err == nil {
			if principal.MustChange {
				http.Redirect(w, r, "/password", http.StatusSeeOther)
			} else {
				http.Redirect(w, r, "/", http.StatusSeeOther)
			}
			return
		}
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Header().Set("Cache-Control", "no-store")
		_ = managerLoginTemplate.Execute(w, nil)
	}
}

func managerPasswordPageHandler(auth *websession.Auth) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/password" {
			http.NotFound(w, r)
			return
		}
		principal, err := auth.Principal(r)
		if err != nil {
			http.Redirect(w, r, "/login", http.StatusSeeOther)
			return
		}
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Header().Set("Cache-Control", "no-store")
		_ = managerPasswordTemplate.Execute(w, principal)
	}
}
func managerDashboardHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/" {
			http.NotFound(w, r)
			return
		}
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Header().Set("Cache-Control", "no-store")
		_ = managerDashboardTemplate.Execute(w, nil)
	}
}

var managerLoginTemplate = template.Must(template.New("manager-login").Parse(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>管理端登录 · BossTransfer</title><style>:root{color-scheme:dark;font-family:InterVariable,Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif;font-feature-settings:"cv01","ss03";color:#f7f8f8;background:#08090a}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 50% -20%,rgba(113,112,255,.16),transparent 42%),#08090a}.card{width:min(420px,100%);padding:32px;background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.08);border-radius:10px;box-shadow:0 28px 90px rgba(0,0,0,.42)}.logo{font-size:25px;font-weight:590;letter-spacing:-.55px;color:#f7f8f8;margin-bottom:7px}.logo:after{content:" / CONTROL";color:#7170ff;font:510 11px ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:.08em}.sub{color:#8a8f98;margin:0 0 25px;line-height:1.6;font-size:14px}label{display:block;color:#d0d6e0;font-size:12px;font-weight:510;margin:15px 0 7px}input{width:100%;min-height:48px;border:1px solid rgba(255,255,255,.1);border-radius:6px;padding:0 13px;font:inherit;background:rgba(255,255,255,.025);color:#f7f8f8;outline:none}input:focus{border-color:#7170ff;box-shadow:0 0 0 3px rgba(113,112,255,.12)}button{width:100%;min-height:48px;margin-top:22px;border:0;border-radius:6px;background:#5e6ad2;color:#fff;font:590 14px inherit;cursor:pointer}button:hover{background:#7170ff}.hint{margin-top:18px;padding:12px 13px;border:1px solid rgba(113,112,255,.18);border-radius:6px;background:rgba(113,112,255,.07);color:#8a8f98;font-size:12px;line-height:1.7}.error{min-height:20px;margin-top:11px;color:#ef8b91;font-size:13px;font-weight:510}</style></head><body><main class="card"><div class="logo">BossTransfer 管理端</div><p class="sub">登录中央授权控制台。</p><form id="form"><label>账号</label><input id="user" autocomplete="username" autofocus><label>密码</label><input id="pass" type="password" autocomplete="current-password"><button>登录</button><div class="error" id="error"></div></form><div class="hint">新安装默认账号为 admin，密码为 password。首次登录后必须先设置自己的账号密码。</div></main><script>const usernameInput=document.getElementById('user'),passwordInput=document.getElementById('pass');document.getElementById('form').onsubmit=async e=>{e.preventDefault();const box=document.getElementById('error');box.textContent='';try{const r=await fetch('/api/v1/manager/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:usernameInput.value,password:passwordInput.value})});const d=await r.json();if(!r.ok)throw new Error(d.message||'登录失败');location.href=d.must_change?'/password':'/'}catch(err){box.textContent=err.message}};</script></body></html>`))

var managerPasswordTemplate = template.Must(template.New("manager-password").Parse(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>设置管理账号 · BossTransfer</title><style>:root{color-scheme:dark;font-family:InterVariable,Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif;font-feature-settings:"cv01","ss03";color:#f7f8f8;background:#08090a}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 50% -20%,rgba(113,112,255,.16),transparent 42%),#08090a}.card{width:min(450px,100%);padding:32px;background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.08);border-radius:10px;box-shadow:0 28px 90px rgba(0,0,0,.42)}h1{margin:0 0 9px;font-size:27px;font-weight:510;letter-spacing:-.55px}.sub{color:#8a8f98;line-height:1.65;margin:0 0 23px;font-size:14px}label{display:block;color:#d0d6e0;font-size:12px;font-weight:510;margin:14px 0 7px}input{width:100%;min-height:48px;border:1px solid rgba(255,255,255,.1);border-radius:6px;padding:0 13px;font:inherit;background:rgba(255,255,255,.025);color:#f7f8f8;outline:none}input:focus{border-color:#7170ff;box-shadow:0 0 0 3px rgba(113,112,255,.12)}button{width:100%;min-height:48px;margin-top:22px;border:0;border-radius:6px;background:#5e6ad2;color:#fff;font:590 14px inherit;cursor:pointer}button:hover{background:#7170ff}.error{min-height:20px;margin-top:11px;color:#ef8b91;font-size:13px;font-weight:510}</style></head><body><main class="card"><h1>先设置管理账号</h1><p class="sub">默认密码只用于首次进入。保存后即可绑定 115 资源账号并签发客户授权码。</p><form id="form"><label for="user">新账号</label><input id="user" value="{{.Username}}" autocomplete="username" required><label for="current">当前密码</label><input id="current" type="password" autocomplete="current-password" required autofocus><label for="password">新密码</label><input id="password" type="password" autocomplete="new-password" minlength="8" required><button type="submit">保存并重新登录</button><div class="error" id="error"></div></form></main><script>document.getElementById('form').onsubmit=async e=>{e.preventDefault();const box=document.getElementById('error');box.textContent='';try{const r=await fetch('/api/v1/manager/auth/credentials',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:document.getElementById('user').value,current_password:document.getElementById('current').value,password:document.getElementById('password').value})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'保存失败');location.href='/login'}catch(err){box.textContent=err.message}};</script></body></html>`))

var managerDashboardTemplate = template.Must(template.New("manager-dashboard").Parse(`<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>BossTransfer 管理端</title>
<style>
:root{color-scheme:dark;--bg:#08090a;--panel:#0f1011;--panel2:#151617;--line:rgba(255,255,255,.08);--line2:rgba(255,255,255,.13);--text:#f7f8f8;--muted:#8a8f98;--accent:#5e6ad2;--accent2:#7170ff;--ok:#4fbd91;--warn:#e7a84b;--bad:#e16b72;font-family:InterVariable,Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif;font-feature-settings:"cv01","ss03"}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 70% -30%,rgba(113,112,255,.13),transparent 42%),var(--bg);color:var(--text)}button,input{font:inherit}button{cursor:pointer}.shell{max-width:1180px;margin:auto;padding:0 24px}.top{position:sticky;top:0;z-index:20;border-bottom:1px solid var(--line);background:rgba(8,9,10,.86);backdrop-filter:blur(18px)}.top .shell{height:62px;display:flex;align-items:center;gap:26px}.brand{font-size:17px;font-weight:620;letter-spacing:-.3px}.brand span{color:var(--accent2);font:520 10px ui-monospace,SFMono-Regular,Consolas,monospace;margin-left:7px;letter-spacing:.08em}.nav{display:flex;gap:4px}.nav a{padding:8px 10px;color:var(--muted);text-decoration:none;font-size:13px;border-radius:6px}.nav a:hover{color:var(--text);background:rgba(255,255,255,.045)}.logout{margin-left:auto;border:0;background:transparent;color:var(--muted);font-size:13px;padding:8px}
main{padding:64px 24px 90px}.hero{max-width:760px;margin-bottom:35px}.eyebrow{color:#9b9aff;font:520 11px ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:.12em;text-transform:uppercase}.hero h1{margin:11px 0 12px;font-size:clamp(32px,5vw,52px);font-weight:520;letter-spacing:-1.8px;line-height:1.08}.hero p{margin:0;color:var(--muted);line-height:1.75;font-size:15px}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;margin-top:28px;background:var(--line);border:1px solid var(--line);border-radius:8px;overflow:hidden}.step{padding:14px;background:var(--panel)}.step b{display:block;font-size:12px;font-weight:560}.step span{display:block;margin-top:4px;color:var(--muted);font-size:11px}
.stack{display:grid;gap:18px}.card{background:linear-gradient(180deg,rgba(255,255,255,.018),transparent),var(--panel);border:1px solid var(--line);border-radius:9px;overflow:hidden}.card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding:22px 24px;border-bottom:1px solid var(--line)}h2{margin:0;font-size:17px;font-weight:570;letter-spacing:-.25px}.desc{margin-top:6px;color:var(--muted);font-size:13px;line-height:1.6}.badge{display:inline-flex;align-items:center;gap:7px;padding:6px 9px;border:1px solid rgba(79,189,145,.26);border-radius:999px;color:var(--ok);background:rgba(79,189,145,.07);font-size:11px;white-space:nowrap}.badge:before{content:"";width:6px;height:6px;border-radius:50%;background:currentColor}.badge.off{color:var(--warn);border-color:rgba(231,168,75,.25);background:rgba(231,168,75,.07)}.body{padding:24px}.grid{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:end}.field label{display:block;margin-bottom:7px;color:#c6cad1;font-size:12px}.field input{width:100%;min-height:44px;padding:0 12px;color:var(--text);background:rgba(255,255,255,.025);border:1px solid var(--line2);border-radius:6px;outline:none}.field input:focus{border-color:var(--accent2);box-shadow:0 0 0 3px rgba(113,112,255,.1)}.help{margin-top:8px;color:var(--muted);font-size:11px;line-height:1.6}.btn{min-height:42px;padding:0 14px;border:1px solid transparent;border-radius:6px;color:#fff;background:var(--accent);font-weight:560;font-size:13px}.btn:hover{background:var(--accent2)}.btn.secondary{background:rgba(255,255,255,.035);border-color:var(--line2);color:#d8dce3}.btn.danger{background:rgba(225,107,114,.07);border-color:rgba(225,107,114,.24);color:#f08e94}.btn.small{min-height:34px;padding:0 10px;font-size:12px}.btn:disabled{opacity:.45;cursor:not-allowed}.account-line{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:15px 16px;background:var(--panel2);border:1px solid var(--line);border-radius:7px}.account-line strong{font-size:14px}.account-line span{display:block;color:var(--muted);font-size:12px;margin-top:4px}.actions{display:flex;gap:8px;flex-wrap:wrap}
.browser{margin-top:16px;border:1px solid var(--line);border-radius:7px;overflow:hidden}.browser-head{min-height:48px;padding:9px 12px;background:rgba(255,255,255,.025);display:flex;align-items:center;justify-content:space-between;gap:10px}.crumb{font-size:12px;color:#c9cdd5;overflow-wrap:anywhere}.folders{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;padding:12px}.folder{min-height:56px;padding:10px 11px;text-align:left;color:#dfe2e8;background:var(--panel2);border:1px solid var(--line);border-radius:6px}.folder:hover{border-color:rgba(113,112,255,.5)}.folder small{display:block;margin-top:4px;color:var(--muted)}.empty{padding:28px;text-align:center;color:var(--muted);font-size:13px}.toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px}.toolbar input{width:min(280px,100%)}.table-wrap{overflow-x:auto}.table{width:100%;border-collapse:collapse;min-width:760px}.table th{padding:11px 15px;color:var(--muted);font-size:11px;font-weight:520;text-align:left;background:rgba(255,255,255,.018)}.table td{padding:14px 15px;border-top:1px solid var(--line);font-size:13px;vertical-align:middle}.name{font-weight:570}.muted{color:var(--muted);font-size:12px}.status-active{color:var(--ok)}.status-revoked,.status-expired{color:var(--bad)}
.modal{position:fixed;inset:0;z-index:50;display:grid;place-items:center;padding:20px;background:rgba(0,0,0,.7);backdrop-filter:blur(8px)}.hidden{display:none!important}.modal-card{width:min(460px,100%);max-height:90vh;overflow:auto;padding:24px;background:#111213;border:1px solid var(--line2);border-radius:9px;box-shadow:0 30px 100px #000}.modal-card h2{font-size:19px;margin-bottom:8px}.modal-card .field{margin-top:14px}.qr{display:block;width:220px;height:220px;margin:18px auto;background:#fff;border-radius:8px;object-fit:contain}.qr-status{text-align:center;color:var(--muted);font-size:13px}.code{margin:18px 0;padding:16px;border:1px dashed rgba(113,112,255,.5);border-radius:7px;color:#c6c5ff;background:rgba(113,112,255,.07);font:600 17px ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere;text-align:center}.toast{position:fixed;left:50%;bottom:26px;z-index:80;transform:translate(-50%,20px);opacity:0;padding:10px 14px;border:1px solid var(--line2);border-radius:7px;background:#202224;color:#fff;font-size:13px;transition:.2s;pointer-events:none}.toast.show{opacity:1;transform:translate(-50%,0)}
@media(max-width:760px){html,body{max-width:100%;overflow-x:hidden}.shell{width:100%;min-width:0;padding:0 16px}.top .shell{height:auto;min-height:58px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px 12px;padding-top:10px;padding-bottom:10px}.brand{min-width:0}.logout{margin:0}.nav{grid-column:1/-1;grid-row:2;width:100%;min-width:0;overflow-x:auto}.nav a{white-space:nowrap}main{padding:40px 16px 70px}.hero,.stack,.card,.body,.grid,.field{min-width:0}.steps{grid-template-columns:1fr}.card-head{align-items:flex-start;flex-direction:column}.card-head,.body{padding:18px}.card-head>.badge,.card-head>.btn{align-self:flex-start}.grid{grid-template-columns:minmax(0,1fr)}#account-form{grid-template-columns:minmax(0,1fr)!important}.field input{min-width:0;max-width:100%}.browser-head{flex-wrap:wrap}.crumb{order:3;width:100%}.folders{grid-template-columns:1fr}.toolbar{align-items:stretch;flex-direction:column}.toolbar input{width:100%}.table{min-width:0}.table thead{display:none}.table,.table tbody,.table tr,.table td{display:block}.table tr{padding:14px 16px;border-top:1px solid var(--line)}.table td{padding:5px 0;border:0;display:grid;grid-template-columns:94px minmax(0,1fr);gap:8px}.table td:before{content:attr(data-label);color:var(--muted);font-size:11px}.table td:first-child{display:block}.table td:first-child:before{display:none}.account-line{align-items:flex-start;flex-direction:column}}
</style></head>
<body>
<header class="top"><div class="shell"><div class="brand">BossTransfer <span>CONTROL</span></div><nav class="nav"><a href="#resource">115 资源</a><a href="#customers">客户授权</a><a href="#account">管理账号</a></nav><button class="logout" id="logout">退出</button></div></header>
<main class="shell"><section class="hero"><div class="eyebrow">Manager console</div><h1>只管理资源与客户授权</h1><p>管理员绑定自己的 115 资源库并签发授权码。客户的 115、保存位置和下载器都由客户在自己的 NAS 上设置。</p><div class="steps"><div class="step"><b>1 · 绑定资源 115</b><span>供授权客户搜索影视文件</span></div><div class="step"><b>2 · 创建客户授权</b><span>生成一次性在线激活码</span></div><div class="step"><b>3 · 客户自行下载</b><span>秒传到客户 115 后下载到本地</span></div></div></section>
<div class="stack">
<section class="card" id="resource"><div class="card-head"><div><h2>115 资源库</h2><div class="desc">使用你自己的 115 Open AppID 扫码绑定资源账号，并选择允许搜索的目录。</div></div><span class="badge off" id="resource-badge">未绑定</span></div><div class="body"><div id="resource-unbound"><div class="grid"><div class="field"><label for="app-id">115 Open AppID</label><input id="app-id" placeholder="在 115 开放平台申请的 AppID" inputmode="numeric"><div class="help">AppID 会提供给已授权客户端发起官方扫码绑定；访问令牌不会下发。</div></div><button class="btn" id="bind-115">扫码绑定</button></div></div><div class="hidden" id="resource-bound"><div class="account-line"><div><strong id="resource-user">已绑定</strong><span id="resource-folder">搜索范围：根目录</span></div><div class="actions"><button class="btn secondary small" id="choose-resource">选择搜索目录</button><button class="btn danger small" id="unbind-resource">解除绑定</button></div></div><div class="browser hidden" id="resource-browser"><div class="browser-head"><button class="btn secondary small" id="resource-up">返回上级</button><span class="crumb" id="resource-path">根目录</span><button class="btn small" id="resource-use">使用当前目录</button></div><div class="folders" id="resource-folders"></div></div></div></div></section>
<section class="card" id="customers"><div class="card-head"><div><h2>客户授权</h2><div class="desc">创建客户、设置有效期和可激活设备数。下载方式由客户自己配置。</div></div><button class="btn" id="add-customer">新增客户</button></div><div class="body"><div class="toolbar"><div class="muted" id="customer-count">0 位客户</div><div class="field"><input id="filter" placeholder="搜索客户"></div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>客户</th><th>状态</th><th>有效期</th><th>设备</th><th>操作</th></tr></thead><tbody id="licenses"><tr><td class="empty" colspan="5">正在加载…</td></tr></tbody></table></div></section>
<section class="card" id="account"><div class="card-head"><div><h2>管理账号</h2><div class="desc">修改本地控制台账号，保存后会重新登录。</div></div></div><div class="body"><form class="grid" id="account-form" style="grid-template-columns:repeat(3,1fr) auto"><div class="field"><label>新账号</label><input id="account-user"></div><div class="field"><label>当前密码</label><input id="account-current" type="password"></div><div class="field"><label>新密码</label><input id="account-password" type="password" minlength="8"></div><button class="btn">保存</button></form></div></section>
</div></main>
<div class="modal hidden" id="qr-modal"><div class="modal-card"><h2>使用 115 手机客户端扫码</h2><p class="desc">扫码后请在手机上确认授权，此页面会自动完成绑定。</p><img class="qr" id="qr-image" alt="115 授权二维码"><div class="qr-status" id="qr-status">等待扫码</div><div class="actions" style="margin-top:18px;justify-content:center"><button class="btn secondary" data-close="qr-modal">取消</button></div></div></div>
<div class="modal hidden" id="grant-modal"><div class="modal-card"><h2 id="grant-title">新增客户</h2><p class="desc">授权码只显示一次，请生成后立即交给客户。</p><form id="grant-form"><input id="grant-id" type="hidden"><div class="field" id="customer-field"><label>客户名称</label><input id="grant-customer" maxlength="256" placeholder="例如：张先生" required></div><div class="field"><label>授权到期日</label><input id="grant-expiry" type="date"></div><div class="field"><label>可激活设备数</label><input id="grant-limit" type="number" min="1" max="10000" value="1" required></div><div class="actions" style="margin-top:20px"><button class="btn">保存授权</button><button class="btn secondary" type="button" data-close="grant-modal">取消</button></div></form></div></div>
<div class="modal hidden" id="code-modal"><div class="modal-card"><h2>客户激活码</h2><p class="desc">完整激活码关闭后不会再次显示。</p><div class="code" id="issued-code"></div><div class="actions"><button class="btn" id="copy-code">复制激活码</button><button class="btn secondary" data-close="code-modal">完成</button></div></div></div>
<div class="toast" id="toast"></div>
<script>
const state={catalog:{},licenses:[],filter:'',browser:[{id:'0',name:'根目录'}],qrTimer:null};
const byId=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,options){const response=await fetch(url,options);let data={};try{data=await response.json()}catch{}if(response.status===401){location.href='/login';throw new Error('登录已过期')}if(!response.ok)throw new Error(data.message||data.error||'请求失败');return data}
function toast(message){const node=byId('toast');node.textContent=message;node.classList.add('show');clearTimeout(node.timer);node.timer=setTimeout(()=>node.classList.remove('show'),2600)}
function dateValue(value){if(!value)return '';return new Date(value).toISOString().slice(0,10)}
async function load(){const [catalog,licenses,session]=await Promise.all([api('/api/v1/manager/catalog'),api('/api/v1/manager/licenses'),api('/api/v1/manager/auth/session')]);state.catalog=catalog.catalog||{};state.licenses=licenses.licenses||[];byId('account-user').value=session.username||'';renderResource();renderLicenses()}
function renderResource(){const c=state.catalog;byId('app-id').value=c.client_id||'';byId('resource-unbound').classList.toggle('hidden',c.bound);byId('resource-bound').classList.toggle('hidden',!c.bound);byId('resource-badge').className='badge '+(c.bound?'':'off');byId('resource-badge').textContent=c.bound?'可供客户搜索':'未绑定';byId('resource-user').textContent=c.user_name||('115 用户 '+(c.user_id||''));byId('resource-folder').textContent='搜索范围：'+(c.folder_name||'根目录')}
async function start115(){const button=byId('bind-115');button.disabled=true;try{const data=await api('/api/v1/manager/115/auth/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id:byId('app-id').value.trim()})});state.catalog=data.catalog||state.catalog;const auth=data.auth;byId('qr-image').src=auth.qr_image_url;byId('qr-status').textContent=auth.message||'等待扫码';byId('qr-modal').classList.remove('hidden');clearInterval(state.qrTimer);state.qrTimer=setInterval(poll115,1800);renderResource()}catch(error){toast(error.message)}finally{button.disabled=false}}
async function poll115(){try{const data=await api('/api/v1/manager/115/auth/status');byId('qr-status').textContent=data.auth.message||'等待扫码';if(data.auth.bound){clearInterval(state.qrTimer);byId('qr-modal').classList.add('hidden');state.catalog=data.catalog;renderResource();toast('115 资源账号已绑定')}}catch(error){clearInterval(state.qrTimer);toast(error.message)}}
async function browseResource(){state.browser=[{id:'0',name:'根目录'}];byId('resource-browser').classList.remove('hidden');await loadResourceFolders()}
async function loadResourceFolders(){const current=state.browser[state.browser.length-1];byId('resource-path').textContent=state.browser.map(x=>x.name).join(' / ');byId('resource-up').disabled=state.browser.length===1;byId('resource-use').textContent='使用“'+current.name+'”';byId('resource-folders').innerHTML='<div class="empty">正在读取目录…</div>';try{const data=await api('/api/v1/manager/115/directories?cid='+encodeURIComponent(current.id));const dirs=data.directories||[];byId('resource-folders').innerHTML=dirs.length?dirs.map(x=>'<button class="folder" data-folder-id="'+esc(x.id)+'" data-folder-name="'+esc(x.name)+'"><strong>▱ '+esc(x.name)+'</strong><small>进入目录</small></button>').join(''):'<div class="empty">当前目录没有子文件夹，可直接选择当前目录。</div>'}catch(error){byId('resource-folders').innerHTML='<div class="empty">'+esc(error.message)+'</div>'}}
function renderLicenses(){const query=state.filter.toLowerCase();const values=state.licenses.filter(x=>!query||String(x.customer).toLowerCase().includes(query));byId('customer-count').textContent=values.length+' 位客户';byId('licenses').innerHTML=values.length?values.map(item=>{const devices=(item.devices||[]).filter(x=>x.status==='active');const expiry=item.expires_at?new Date(item.expires_at).toLocaleDateString():'长期';const actions='<button class="btn secondary small" data-edit="'+esc(item.id)+'">编辑</button><button class="btn secondary small" data-code="'+esc(item.id)+'">新激活码</button>'+(devices.map(d=>'<button class="btn secondary small" data-release="'+esc(d.id)+'">释放 '+esc(d.label||'设备')+'</button>').join(''))+(item.status==='active'?'<button class="btn danger small" data-revoke="'+esc(item.id)+'">撤销</button>':'');return '<tr><td data-label="客户"><div class="name">'+esc(item.customer)+'</div><div class="muted">'+esc(item.id)+'</div></td><td data-label="状态"><span class="status-'+esc(item.status)+'">'+esc(item.status)+'</span></td><td data-label="有效期">'+esc(expiry)+'</td><td data-label="设备">'+devices.length+' / '+item.device_limit+'</td><td data-label="操作"><div class="actions">'+actions+'</div></td></tr>'}).join(''):'<tr><td class="empty" colspan="5">还没有客户，点击“新增客户”生成第一枚激活码。</td></tr>'}
function openGrant(item){byId('grant-id').value=item?item.id:'';byId('grant-title').textContent=item?'编辑客户授权':'新增客户';byId('grant-customer').value=item?item.customer:'';byId('grant-customer').disabled=Boolean(item);byId('customer-field').classList.toggle('hidden',Boolean(item));byId('grant-expiry').value=item?dateValue(item.expires_at):dateValue(Date.now()+365*86400000);byId('grant-limit').value=item?item.device_limit:1;byId('grant-modal').classList.remove('hidden')}
function showCode(code){byId('issued-code').textContent=code;byId('code-modal').classList.remove('hidden')}
byId('bind-115').onclick=start115;byId('choose-resource').onclick=browseResource;byId('resource-up').onclick=()=>{if(state.browser.length>1){state.browser.pop();loadResourceFolders()}};byId('resource-folders').onclick=event=>{const folder=event.target.closest('[data-folder-id]');if(folder){state.browser.push({id:folder.dataset.folderId,name:folder.dataset.folderName});loadResourceFolders()}};byId('resource-use').onclick=async()=>{const current=state.browser[state.browser.length-1];try{const data=await api('/api/v1/manager/catalog',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({folder_id:current.id,folder_name:current.name})});state.catalog=data.catalog;renderResource();byId('resource-browser').classList.add('hidden');toast('客户搜索范围已保存')}catch(error){toast(error.message)}};byId('unbind-resource').onclick=async()=>{if(!confirm('确认解除资源 115 账号？客户将暂时无法搜索。'))return;try{const data=await api('/api/v1/manager/115/account',{method:'DELETE',headers:{'Content-Type':'application/json'},body:'{}'});state.catalog=data.catalog;renderResource();toast('已解除绑定')}catch(error){toast(error.message)}};
byId('add-customer').onclick=()=>openGrant(null);byId('filter').oninput=event=>{state.filter=event.target.value.trim();renderLicenses()};byId('licenses').onclick=async event=>{const edit=event.target.closest('[data-edit]'),code=event.target.closest('[data-code]'),release=event.target.closest('[data-release]'),revoke=event.target.closest('[data-revoke]');try{if(edit)openGrant(state.licenses.find(x=>x.id===edit.dataset.edit));if(code){const data=await api('/api/v1/manager/licenses/'+encodeURIComponent(code.dataset.code)+'/codes',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});showCode(data.authorization_code)}if(release){if(confirm('确认释放这台设备？')){await api('/api/v1/manager/devices/'+encodeURIComponent(release.dataset.release)+'/release',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await load();toast('设备已释放')}}if(revoke){if(confirm('确认撤销这个客户的授权？')){await api('/api/v1/manager/licenses/'+encodeURIComponent(revoke.dataset.revoke)+'/revoke',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await load();toast('授权已撤销')}}}catch(error){toast(error.message)}};
byId('grant-form').onsubmit=async event=>{event.preventDefault();const id=byId('grant-id').value;const expiry=byId('grant-expiry').value;const payload={expires_at:expiry?new Date(expiry+'T23:59:59Z').toISOString():null,device_limit:Number(byId('grant-limit').value)};try{if(id){const data=await api('/api/v1/manager/licenses/'+encodeURIComponent(id),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});state.licenses=state.licenses.map(x=>x.id===id?data.license:x);byId('grant-modal').classList.add('hidden');renderLicenses();toast('客户授权已更新')}else{payload.customer=byId('grant-customer').value.trim();const data=await api('/api/v1/manager/licenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});state.licenses.push(data.license);byId('grant-modal').classList.add('hidden');renderLicenses();showCode(data.code.authorization_code)}}catch(error){toast(error.message)}};
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>{const id=button.dataset.close;byId(id).classList.add('hidden');if(id==='qr-modal')clearInterval(state.qrTimer)});byId('copy-code').onclick=async()=>{try{await navigator.clipboard.writeText(byId('issued-code').textContent);toast('激活码已复制')}catch{toast('复制失败，请手动复制')}};byId('account-form').onsubmit=async event=>{event.preventDefault();try{await api('/api/v1/manager/auth/credentials',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:byId('account-user').value,current_password:byId('account-current').value,password:byId('account-password').value})});location.href='/login'}catch(error){toast(error.message)}};byId('logout').onclick=async()=>{await api('/api/v1/manager/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});location.href='/login'};load().catch(error=>toast(error.message));
</script></body></html>`))
