// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: clouddrive.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloudDriveFile_FileType int32

const (
	CloudDriveFile_Directory CloudDriveFile_FileType = 0
	CloudDriveFile_File      CloudDriveFile_FileType = 1
	CloudDriveFile_Other     CloudDriveFile_FileType = 2
)

// Enum value maps for CloudDriveFile_FileType.
var (
	CloudDriveFile_FileType_name = map[int32]string{
		0: "Directory",
		1: "File",
		2: "Other",
	}
	CloudDriveFile_FileType_value = map[string]int32{
		"Directory": 0,
		"File":      1,
		"Other":     2,
	}
)

func (x CloudDriveFile_FileType) Enum() *CloudDriveFile_FileType {
	p := new(CloudDriveFile_FileType)
	*p = x
	return p
}

func (x CloudDriveFile_FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloudDriveFile_FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_clouddrive_proto_enumTypes[0].Descriptor()
}

func (CloudDriveFile_FileType) Type() protoreflect.EnumType {
	return &file_clouddrive_proto_enumTypes[0]
}

func (x CloudDriveFile_FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloudDriveFile_FileType.Descriptor instead.
func (CloudDriveFile_FileType) EnumDescriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{8, 0}
}

type CopyFileRequest_ConflictPolicy int32

const (
	CopyFileRequest_Overwrite CopyFileRequest_ConflictPolicy = 0
	CopyFileRequest_Rename    CopyFileRequest_ConflictPolicy = 1
	CopyFileRequest_Skip      CopyFileRequest_ConflictPolicy = 2
)

// Enum value maps for CopyFileRequest_ConflictPolicy.
var (
	CopyFileRequest_ConflictPolicy_name = map[int32]string{
		0: "Overwrite",
		1: "Rename",
		2: "Skip",
	}
	CopyFileRequest_ConflictPolicy_value = map[string]int32{
		"Overwrite": 0,
		"Rename":    1,
		"Skip":      2,
	}
)

func (x CopyFileRequest_ConflictPolicy) Enum() *CopyFileRequest_ConflictPolicy {
	p := new(CopyFileRequest_ConflictPolicy)
	*p = x
	return p
}

func (x CopyFileRequest_ConflictPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CopyFileRequest_ConflictPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_clouddrive_proto_enumTypes[1].Descriptor()
}

func (CopyFileRequest_ConflictPolicy) Type() protoreflect.EnumType {
	return &file_clouddrive_proto_enumTypes[1]
}

func (x CopyFileRequest_ConflictPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CopyFileRequest_ConflictPolicy.Descriptor instead.
func (CopyFileRequest_ConflictPolicy) EnumDescriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{10, 0}
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TotpCode      *string                `protobuf:"bytes,3,opt,name=totpCode,proto3,oneof" json:"totpCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_clouddrive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{0}
}

func (x *GetTokenRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetTokenRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetTokenRequest) GetTotpCode() string {
	if x != nil && x.TotpCode != nil {
		return *x.TotpCode
	}
	return ""
}

type JWTToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTToken) Reset() {
	*x = JWTToken{}
	mi := &file_clouddrive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTToken) ProtoMessage() {}

func (x *JWTToken) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTToken.ProtoReflect.Descriptor instead.
func (*JWTToken) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{1}
}

func (x *JWTToken) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JWTToken) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JWTToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JWTToken) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type CloudDriveSystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLogin       bool                   `protobuf:"varint,1,opt,name=IsLogin,proto3" json:"IsLogin,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	SystemReady   bool                   `protobuf:"varint,3,opt,name=SystemReady,proto3" json:"SystemReady,omitempty"`
	SystemMessage *string                `protobuf:"bytes,4,opt,name=SystemMessage,proto3,oneof" json:"SystemMessage,omitempty"`
	HasError      *bool                  `protobuf:"varint,5,opt,name=hasError,proto3,oneof" json:"hasError,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudDriveSystemInfo) Reset() {
	*x = CloudDriveSystemInfo{}
	mi := &file_clouddrive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudDriveSystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudDriveSystemInfo) ProtoMessage() {}

func (x *CloudDriveSystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudDriveSystemInfo.ProtoReflect.Descriptor instead.
func (*CloudDriveSystemInfo) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{2}
}

func (x *CloudDriveSystemInfo) GetIsLogin() bool {
	if x != nil {
		return x.IsLogin
	}
	return false
}

func (x *CloudDriveSystemInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CloudDriveSystemInfo) GetSystemReady() bool {
	if x != nil {
		return x.SystemReady
	}
	return false
}

func (x *CloudDriveSystemInfo) GetSystemMessage() string {
	if x != nil && x.SystemMessage != nil {
		return *x.SystemMessage
	}
	return ""
}

func (x *CloudDriveSystemInfo) GetHasError() bool {
	if x != nil && x.HasError != nil {
		return *x.HasError
	}
	return false
}

type StringValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringValue) Reset() {
	*x = StringValue{}
	mi := &file_clouddrive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValue) ProtoMessage() {}

func (x *StringValue) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValue.ProtoReflect.Descriptor instead.
func (*StringValue) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{3}
}

func (x *StringValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TokenPermissions struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	AllowList               bool                   `protobuf:"varint,1,opt,name=allow_list,json=allowList,proto3" json:"allow_list,omitempty"`
	AllowSearch             bool                   `protobuf:"varint,2,opt,name=allow_search,json=allowSearch,proto3" json:"allow_search,omitempty"`
	AllowListLocal          bool                   `protobuf:"varint,3,opt,name=allow_list_local,json=allowListLocal,proto3" json:"allow_list_local,omitempty"`
	AllowRead               bool                   `protobuf:"varint,7,opt,name=allow_read,json=allowRead,proto3" json:"allow_read,omitempty"`
	AllowCopy               bool                   `protobuf:"varint,10,opt,name=allow_copy,json=allowCopy,proto3" json:"allow_copy,omitempty"`
	AllowAddOfflineDownload bool                   `protobuf:"varint,16,opt,name=allow_add_offline_download,json=allowAddOfflineDownload,proto3" json:"allow_add_offline_download,omitempty"`
	AllowSharedLinks        bool                   `protobuf:"varint,19,opt,name=allow_shared_links,json=allowSharedLinks,proto3" json:"allow_shared_links,omitempty"`
	AllowGetMounts          bool                   `protobuf:"varint,25,opt,name=allow_get_mounts,json=allowGetMounts,proto3" json:"allow_get_mounts,omitempty"`
	AllowGetTransferTasks   bool                   `protobuf:"varint,27,opt,name=allow_get_transfer_tasks,json=allowGetTransferTasks,proto3" json:"allow_get_transfer_tasks,omitempty"`
	AllowGetCloudApis       bool                   `protobuf:"varint,29,opt,name=allow_get_cloud_apis,json=allowGetCloudApis,proto3" json:"allow_get_cloud_apis,omitempty"`
	AllowPushMessage        bool                   `protobuf:"varint,41,opt,name=allow_push_message,json=allowPushMessage,proto3" json:"allow_push_message,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TokenPermissions) Reset() {
	*x = TokenPermissions{}
	mi := &file_clouddrive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPermissions) ProtoMessage() {}

func (x *TokenPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPermissions.ProtoReflect.Descriptor instead.
func (*TokenPermissions) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{4}
}

func (x *TokenPermissions) GetAllowList() bool {
	if x != nil {
		return x.AllowList
	}
	return false
}

func (x *TokenPermissions) GetAllowSearch() bool {
	if x != nil {
		return x.AllowSearch
	}
	return false
}

func (x *TokenPermissions) GetAllowListLocal() bool {
	if x != nil {
		return x.AllowListLocal
	}
	return false
}

func (x *TokenPermissions) GetAllowRead() bool {
	if x != nil {
		return x.AllowRead
	}
	return false
}

func (x *TokenPermissions) GetAllowCopy() bool {
	if x != nil {
		return x.AllowCopy
	}
	return false
}

func (x *TokenPermissions) GetAllowAddOfflineDownload() bool {
	if x != nil {
		return x.AllowAddOfflineDownload
	}
	return false
}

func (x *TokenPermissions) GetAllowSharedLinks() bool {
	if x != nil {
		return x.AllowSharedLinks
	}
	return false
}

func (x *TokenPermissions) GetAllowGetMounts() bool {
	if x != nil {
		return x.AllowGetMounts
	}
	return false
}

func (x *TokenPermissions) GetAllowGetTransferTasks() bool {
	if x != nil {
		return x.AllowGetTransferTasks
	}
	return false
}

func (x *TokenPermissions) GetAllowGetCloudApis() bool {
	if x != nil {
		return x.AllowGetCloudApis
	}
	return false
}

func (x *TokenPermissions) GetAllowPushMessage() bool {
	if x != nil {
		return x.AllowPushMessage
	}
	return false
}

type ListSubFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ForceRefresh  bool                   `protobuf:"varint,2,opt,name=forceRefresh,proto3" json:"forceRefresh,omitempty"`
	CheckExpires  *bool                  `protobuf:"varint,3,opt,name=checkExpires,proto3,oneof" json:"checkExpires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubFileRequest) Reset() {
	*x = ListSubFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubFileRequest) ProtoMessage() {}

func (x *ListSubFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubFileRequest.ProtoReflect.Descriptor instead.
func (*ListSubFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{5}
}

func (x *ListSubFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListSubFileRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

func (x *ListSubFileRequest) GetCheckExpires() bool {
	if x != nil && x.CheckExpires != nil {
		return *x.CheckExpires
	}
	return false
}

type SearchRequest struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Path                           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SearchFor                      string                 `protobuf:"bytes,2,opt,name=searchFor,proto3" json:"searchFor,omitempty"`
	ForceRefresh                   bool                   `protobuf:"varint,3,opt,name=forceRefresh,proto3" json:"forceRefresh,omitempty"`
	FuzzyMatch                     bool                   `protobuf:"varint,4,opt,name=fuzzyMatch,proto3" json:"fuzzyMatch,omitempty"`
	AddResultToMountedSearchFolder *bool                  `protobuf:"varint,5,opt,name=addResultToMountedSearchFolder,proto3,oneof" json:"addResultToMountedSearchFolder,omitempty"`
	ContentSearch                  *bool                  `protobuf:"varint,6,opt,name=contentSearch,proto3,oneof" json:"contentSearch,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_clouddrive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SearchRequest) GetSearchFor() string {
	if x != nil {
		return x.SearchFor
	}
	return ""
}

func (x *SearchRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

func (x *SearchRequest) GetFuzzyMatch() bool {
	if x != nil {
		return x.FuzzyMatch
	}
	return false
}

func (x *SearchRequest) GetAddResultToMountedSearchFolder() bool {
	if x != nil && x.AddResultToMountedSearchFolder != nil {
		return *x.AddResultToMountedSearchFolder
	}
	return false
}

func (x *SearchRequest) GetContentSearch() bool {
	if x != nil && x.ContentSearch != nil {
		return *x.ContentSearch
	}
	return false
}

type SubFilesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubFiles      []*CloudDriveFile      `protobuf:"bytes,1,rep,name=subFiles,proto3" json:"subFiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubFilesReply) Reset() {
	*x = SubFilesReply{}
	mi := &file_clouddrive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubFilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubFilesReply) ProtoMessage() {}

func (x *SubFilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubFilesReply.ProtoReflect.Descriptor instead.
func (*SubFilesReply) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{7}
}

func (x *SubFilesReply) GetSubFiles() []*CloudDriveFile {
	if x != nil {
		return x.SubFiles
	}
	return nil
}

type CloudDriveFile struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Id                 string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FullPathName       string                  `protobuf:"bytes,3,opt,name=fullPathName,proto3" json:"fullPathName,omitempty"`
	Size               int64                   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	FileType           CloudDriveFile_FileType `protobuf:"varint,5,opt,name=fileType,proto3,enum=clouddrive.CloudDriveFile_FileType" json:"fileType,omitempty"`
	CreateTime         *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	WriteTime          *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=writeTime,proto3" json:"writeTime,omitempty"`
	AccessTime         *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=accessTime,proto3" json:"accessTime,omitempty"`
	ThumbnailUrl       string                  `protobuf:"bytes,10,opt,name=thumbnailUrl,proto3" json:"thumbnailUrl,omitempty"`
	PreviewUrl         string                  `protobuf:"bytes,11,opt,name=previewUrl,proto3" json:"previewUrl,omitempty"`
	OriginalPath       string                  `protobuf:"bytes,14,opt,name=originalPath,proto3" json:"originalPath,omitempty"`
	IsDirectory        bool                    `protobuf:"varint,30,opt,name=isDirectory,proto3" json:"isDirectory,omitempty"`
	IsRoot             bool                    `protobuf:"varint,31,opt,name=isRoot,proto3" json:"isRoot,omitempty"`
	IsCloudRoot        bool                    `protobuf:"varint,32,opt,name=isCloudRoot,proto3" json:"isCloudRoot,omitempty"`
	IsCloudDirectory   bool                    `protobuf:"varint,33,opt,name=isCloudDirectory,proto3" json:"isCloudDirectory,omitempty"`
	IsCloudFile        bool                    `protobuf:"varint,34,opt,name=isCloudFile,proto3" json:"isCloudFile,omitempty"`
	IsSearchResult     bool                    `protobuf:"varint,35,opt,name=isSearchResult,proto3" json:"isSearchResult,omitempty"`
	IsForbidden        bool                    `protobuf:"varint,36,opt,name=isForbidden,proto3" json:"isForbidden,omitempty"`
	CanSearch          bool                    `protobuf:"varint,63,opt,name=canSearch,proto3" json:"canSearch,omitempty"`
	CanOfflineDownload bool                    `protobuf:"varint,66,opt,name=canOfflineDownload,proto3" json:"canOfflineDownload,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CloudDriveFile) Reset() {
	*x = CloudDriveFile{}
	mi := &file_clouddrive_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudDriveFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudDriveFile) ProtoMessage() {}

func (x *CloudDriveFile) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudDriveFile.ProtoReflect.Descriptor instead.
func (*CloudDriveFile) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{8}
}

func (x *CloudDriveFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CloudDriveFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CloudDriveFile) GetFullPathName() string {
	if x != nil {
		return x.FullPathName
	}
	return ""
}

func (x *CloudDriveFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CloudDriveFile) GetFileType() CloudDriveFile_FileType {
	if x != nil {
		return x.FileType
	}
	return CloudDriveFile_Directory
}

func (x *CloudDriveFile) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CloudDriveFile) GetWriteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.WriteTime
	}
	return nil
}

func (x *CloudDriveFile) GetAccessTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTime
	}
	return nil
}

func (x *CloudDriveFile) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *CloudDriveFile) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *CloudDriveFile) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *CloudDriveFile) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *CloudDriveFile) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

func (x *CloudDriveFile) GetIsCloudRoot() bool {
	if x != nil {
		return x.IsCloudRoot
	}
	return false
}

func (x *CloudDriveFile) GetIsCloudDirectory() bool {
	if x != nil {
		return x.IsCloudDirectory
	}
	return false
}

func (x *CloudDriveFile) GetIsCloudFile() bool {
	if x != nil {
		return x.IsCloudFile
	}
	return false
}

func (x *CloudDriveFile) GetIsSearchResult() bool {
	if x != nil {
		return x.IsSearchResult
	}
	return false
}

func (x *CloudDriveFile) GetIsForbidden() bool {
	if x != nil {
		return x.IsForbidden
	}
	return false
}

func (x *CloudDriveFile) GetCanSearch() bool {
	if x != nil {
		return x.CanSearch
	}
	return false
}

func (x *CloudDriveFile) GetCanOfflineDownload() bool {
	if x != nil {
		return x.CanOfflineDownload
	}
	return false
}

type FileOperationResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	ResultFilePaths []string               `protobuf:"bytes,3,rep,name=resultFilePaths,proto3" json:"resultFilePaths,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileOperationResult) Reset() {
	*x = FileOperationResult{}
	mi := &file_clouddrive_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOperationResult) ProtoMessage() {}

func (x *FileOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOperationResult.ProtoReflect.Descriptor instead.
func (*FileOperationResult) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{9}
}

func (x *FileOperationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileOperationResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FileOperationResult) GetResultFilePaths() []string {
	if x != nil {
		return x.ResultFilePaths
	}
	return nil
}

type CopyFileRequest struct {
	state                     protoimpl.MessageState          `protogen:"open.v1"`
	TheFilePaths              []string                        `protobuf:"bytes,1,rep,name=theFilePaths,proto3" json:"theFilePaths,omitempty"`
	DestPath                  string                          `protobuf:"bytes,2,opt,name=destPath,proto3" json:"destPath,omitempty"`
	ConflictPolicy            *CopyFileRequest_ConflictPolicy `protobuf:"varint,3,opt,name=conflictPolicy,proto3,enum=clouddrive.CopyFileRequest_ConflictPolicy,oneof" json:"conflictPolicy,omitempty"`
	HandleConflictRecursively *bool                           `protobuf:"varint,5,opt,name=handleConflictRecursively,proto3,oneof" json:"handleConflictRecursively,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CopyFileRequest) Reset() {
	*x = CopyFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileRequest) ProtoMessage() {}

func (x *CopyFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileRequest.ProtoReflect.Descriptor instead.
func (*CopyFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{10}
}

func (x *CopyFileRequest) GetTheFilePaths() []string {
	if x != nil {
		return x.TheFilePaths
	}
	return nil
}

func (x *CopyFileRequest) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

func (x *CopyFileRequest) GetConflictPolicy() CopyFileRequest_ConflictPolicy {
	if x != nil && x.ConflictPolicy != nil {
		return *x.ConflictPolicy
	}
	return CopyFileRequest_Overwrite
}

func (x *CopyFileRequest) GetHandleConflictRecursively() bool {
	if x != nil && x.HandleConflictRecursively != nil {
		return *x.HandleConflictRecursively
	}
	return false
}

type AddOfflineFileRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Urls                 string                 `protobuf:"bytes,1,opt,name=urls,proto3" json:"urls,omitempty"`
	ToFolder             string                 `protobuf:"bytes,2,opt,name=toFolder,proto3" json:"toFolder,omitempty"`
	CheckFolderAfterSecs *uint64                `protobuf:"varint,3,opt,name=checkFolderAfterSecs,proto3,oneof" json:"checkFolderAfterSecs,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AddOfflineFileRequest) Reset() {
	*x = AddOfflineFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOfflineFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOfflineFileRequest) ProtoMessage() {}

func (x *AddOfflineFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOfflineFileRequest.ProtoReflect.Descriptor instead.
func (*AddOfflineFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{11}
}

func (x *AddOfflineFileRequest) GetUrls() string {
	if x != nil {
		return x.Urls
	}
	return ""
}

func (x *AddOfflineFileRequest) GetToFolder() string {
	if x != nil {
		return x.ToFolder
	}
	return ""
}

func (x *AddOfflineFileRequest) GetCheckFolderAfterSecs() uint64 {
	if x != nil && x.CheckFolderAfterSecs != nil {
		return *x.CheckFolderAfterSecs
	}
	return 0
}

type AddSharedLinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SharedLinkUrl  string                 `protobuf:"bytes,1,opt,name=sharedLinkUrl,proto3" json:"sharedLinkUrl,omitempty"`
	SharedPassword *string                `protobuf:"bytes,2,opt,name=sharedPassword,proto3,oneof" json:"sharedPassword,omitempty"`
	ToFolder       string                 `protobuf:"bytes,3,opt,name=toFolder,proto3" json:"toFolder,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddSharedLinkRequest) Reset() {
	*x = AddSharedLinkRequest{}
	mi := &file_clouddrive_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSharedLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSharedLinkRequest) ProtoMessage() {}

func (x *AddSharedLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSharedLinkRequest.ProtoReflect.Descriptor instead.
func (*AddSharedLinkRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{12}
}

func (x *AddSharedLinkRequest) GetSharedLinkUrl() string {
	if x != nil {
		return x.SharedLinkUrl
	}
	return ""
}

func (x *AddSharedLinkRequest) GetSharedPassword() string {
	if x != nil && x.SharedPassword != nil {
		return *x.SharedPassword
	}
	return ""
}

func (x *AddSharedLinkRequest) GetToFolder() string {
	if x != nil {
		return x.ToFolder
	}
	return ""
}

type GetDownloadUrlPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Preview       bool                   `protobuf:"varint,2,opt,name=preview,proto3" json:"preview,omitempty"`
	LazyRead      bool                   `protobuf:"varint,3,opt,name=lazy_read,json=lazyRead,proto3" json:"lazy_read,omitempty"`
	GetDirectUrl  bool                   `protobuf:"varint,4,opt,name=get_direct_url,json=getDirectUrl,proto3" json:"get_direct_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlPathRequest) Reset() {
	*x = GetDownloadUrlPathRequest{}
	mi := &file_clouddrive_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlPathRequest) ProtoMessage() {}

func (x *GetDownloadUrlPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlPathRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlPathRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{13}
}

func (x *GetDownloadUrlPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetDownloadUrlPathRequest) GetPreview() bool {
	if x != nil {
		return x.Preview
	}
	return false
}

func (x *GetDownloadUrlPathRequest) GetLazyRead() bool {
	if x != nil {
		return x.LazyRead
	}
	return false
}

func (x *GetDownloadUrlPathRequest) GetGetDirectUrl() bool {
	if x != nil {
		return x.GetDirectUrl
	}
	return false
}

type DownloadUrlPathInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrlPath   string                 `protobuf:"bytes,1,opt,name=downloadUrlPath,proto3" json:"downloadUrlPath,omitempty"`
	ExpiresIn         *uint64                `protobuf:"varint,2,opt,name=expiresIn,proto3,oneof" json:"expiresIn,omitempty"`
	DirectUrl         *string                `protobuf:"bytes,3,opt,name=directUrl,proto3,oneof" json:"directUrl,omitempty"`
	UserAgent         *string                `protobuf:"bytes,4,opt,name=userAgent,proto3,oneof" json:"userAgent,omitempty"`
	AdditionalHeaders map[string]string      `protobuf:"bytes,5,rep,name=additionalHeaders,proto3" json:"additionalHeaders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DownloadUrlPathInfo) Reset() {
	*x = DownloadUrlPathInfo{}
	mi := &file_clouddrive_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadUrlPathInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadUrlPathInfo) ProtoMessage() {}

func (x *DownloadUrlPathInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadUrlPathInfo.ProtoReflect.Descriptor instead.
func (*DownloadUrlPathInfo) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{14}
}

func (x *DownloadUrlPathInfo) GetDownloadUrlPath() string {
	if x != nil {
		return x.DownloadUrlPath
	}
	return ""
}

func (x *DownloadUrlPathInfo) GetExpiresIn() uint64 {
	if x != nil && x.ExpiresIn != nil {
		return *x.ExpiresIn
	}
	return 0
}

func (x *DownloadUrlPathInfo) GetDirectUrl() string {
	if x != nil && x.DirectUrl != nil {
		return *x.DirectUrl
	}
	return ""
}

func (x *DownloadUrlPathInfo) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *DownloadUrlPathInfo) GetAdditionalHeaders() map[string]string {
	if x != nil {
		return x.AdditionalHeaders
	}
	return nil
}

type TokenInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Official field 1 contains the token itself. It is intentionally omitted
	// so callers cannot accidentally log a token echoed by the server.
	RootDir       string            `protobuf:"bytes,2,opt,name=rootDir,proto3" json:"rootDir,omitempty"`
	Permissions   *TokenPermissions `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	ExpiresIn     *uint64           `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3,oneof" json:"expires_in,omitempty"`
	FriendlyName  string            `protobuf:"bytes,5,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_clouddrive_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{15}
}

func (x *TokenInfo) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *TokenInfo) GetPermissions() *TokenPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *TokenInfo) GetExpiresIn() uint64 {
	if x != nil && x.ExpiresIn != nil {
		return *x.ExpiresIn
	}
	return 0
}

func (x *TokenInfo) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

type MountPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mountPoint,proto3" json:"mountPoint,omitempty"`
	SourceDir     string                 `protobuf:"bytes,2,opt,name=sourceDir,proto3" json:"sourceDir,omitempty"`
	LocalMount    bool                   `protobuf:"varint,3,opt,name=localMount,proto3" json:"localMount,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,4,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	AutoMount     bool                   `protobuf:"varint,5,opt,name=autoMount,proto3" json:"autoMount,omitempty"`
	Uid           uint32                 `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,7,opt,name=gid,proto3" json:"gid,omitempty"`
	Permissions   string                 `protobuf:"bytes,8,opt,name=permissions,proto3" json:"permissions,omitempty"`
	IsMounted     bool                   `protobuf:"varint,9,opt,name=isMounted,proto3" json:"isMounted,omitempty"`
	FailReason    string                 `protobuf:"bytes,10,opt,name=failReason,proto3" json:"failReason,omitempty"`
	Name          string                 `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountPoint) Reset() {
	*x = MountPoint{}
	mi := &file_clouddrive_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountPoint) ProtoMessage() {}

func (x *MountPoint) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountPoint.ProtoReflect.Descriptor instead.
func (*MountPoint) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{16}
}

func (x *MountPoint) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *MountPoint) GetSourceDir() string {
	if x != nil {
		return x.SourceDir
	}
	return ""
}

func (x *MountPoint) GetLocalMount() bool {
	if x != nil {
		return x.LocalMount
	}
	return false
}

func (x *MountPoint) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *MountPoint) GetAutoMount() bool {
	if x != nil {
		return x.AutoMount
	}
	return false
}

func (x *MountPoint) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MountPoint) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *MountPoint) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

func (x *MountPoint) GetIsMounted() bool {
	if x != nil {
		return x.IsMounted
	}
	return false
}

func (x *MountPoint) GetFailReason() string {
	if x != nil {
		return x.FailReason
	}
	return ""
}

func (x *MountPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMountPointsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoints   []*MountPoint          `protobuf:"bytes,1,rep,name=mountPoints,proto3" json:"mountPoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMountPointsResult) Reset() {
	*x = GetMountPointsResult{}
	mi := &file_clouddrive_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMountPointsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMountPointsResult) ProtoMessage() {}

func (x *GetMountPointsResult) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMountPointsResult.ProtoReflect.Descriptor instead.
func (*GetMountPointsResult) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{17}
}

func (x *GetMountPointsResult) GetMountPoints() []*MountPoint {
	if x != nil {
		return x.MountPoints
	}
	return nil
}

var File_clouddrive_proto protoreflect.FileDescriptor

const file_clouddrive_proto_rawDesc = "" +
	"\n" +
	"\x10clouddrive.proto\x12\n" +
	"clouddrive\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\x0fGetTokenRequest\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\btotpCode\x18\x03 \x01(\tH\x00R\btotpCode\x88\x01\x01B\v\n" +
	"\t_totpCode\"\x9a\x01\n" +
	"\bJWTToken\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12:\n" +
	"\n" +
	"expiration\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\"\xd9\x01\n" +
	"\x14CloudDriveSystemInfo\x12\x18\n" +
	"\aIsLogin\x18\x01 \x01(\bR\aIsLogin\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12 \n" +
	"\vSystemReady\x18\x03 \x01(\bR\vSystemReady\x12)\n" +
	"\rSystemMessage\x18\x04 \x01(\tH\x00R\rSystemMessage\x88\x01\x01\x12\x1f\n" +
	"\bhasError\x18\x05 \x01(\bH\x01R\bhasError\x88\x01\x01B\x10\n" +
	"\x0e_SystemMessageB\v\n" +
	"\t_hasError\"#\n" +
	"\vStringValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xe9\x03\n" +
	"\x10TokenPermissions\x12\x1d\n" +
	"\n" +
	"allow_list\x18\x01 \x01(\bR\tallowList\x12!\n" +
	"\fallow_search\x18\x02 \x01(\bR\vallowSearch\x12(\n" +
	"\x10allow_list_local\x18\x03 \x01(\bR\x0eallowListLocal\x12\x1d\n" +
	"\n" +
	"allow_read\x18\a \x01(\bR\tallowRead\x12\x1d\n" +
	"\n" +
	"allow_copy\x18\n" +
	" \x01(\bR\tallowCopy\x12;\n" +
	"\x1aallow_add_offline_download\x18\x10 \x01(\bR\x17allowAddOfflineDownload\x12,\n" +
	"\x12allow_shared_links\x18\x13 \x01(\bR\x10allowSharedLinks\x12(\n" +
	"\x10allow_get_mounts\x18\x19 \x01(\bR\x0eallowGetMounts\x127\n" +
	"\x18allow_get_transfer_tasks\x18\x1b \x01(\bR\x15allowGetTransferTasks\x12/\n" +
	"\x14allow_get_cloud_apis\x18\x1d \x01(\bR\x11allowGetCloudApis\x12,\n" +
	"\x12allow_push_message\x18) \x01(\bR\x10allowPushMessage\"\x86\x01\n" +
	"\x12ListSubFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\"\n" +
	"\fforceRefresh\x18\x02 \x01(\bR\fforceRefresh\x12'\n" +
	"\fcheckExpires\x18\x03 \x01(\bH\x00R\fcheckExpires\x88\x01\x01B\x0f\n" +
	"\r_checkExpires\"\xb2\x02\n" +
	"\rSearchRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\tsearchFor\x18\x02 \x01(\tR\tsearchFor\x12\"\n" +
	"\fforceRefresh\x18\x03 \x01(\bR\fforceRefresh\x12\x1e\n" +
	"\n" +
	"fuzzyMatch\x18\x04 \x01(\bR\n" +
	"fuzzyMatch\x12K\n" +
	"\x1eaddResultToMountedSearchFolder\x18\x05 \x01(\bH\x00R\x1eaddResultToMountedSearchFolder\x88\x01\x01\x12)\n" +
	"\rcontentSearch\x18\x06 \x01(\bH\x01R\rcontentSearch\x88\x01\x01B!\n" +
	"\x1f_addResultToMountedSearchFolderB\x10\n" +
	"\x0e_contentSearch\"G\n" +
	"\rSubFilesReply\x126\n" +
	"\bsubFiles\x18\x01 \x03(\v2\x1a.clouddrive.CloudDriveFileR\bsubFiles\"\xb9\x06\n" +
	"\x0eCloudDriveFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\ffullPathName\x18\x03 \x01(\tR\ffullPathName\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12?\n" +
	"\bfileType\x18\x05 \x01(\x0e2#.clouddrive.CloudDriveFile.FileTypeR\bfileType\x12:\n" +
	"\n" +
	"createTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x128\n" +
	"\twriteTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\twriteTime\x12:\n" +
	"\n" +
	"accessTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"accessTime\x12\"\n" +
	"\fthumbnailUrl\x18\n" +
	" \x01(\tR\fthumbnailUrl\x12\x1e\n" +
	"\n" +
	"previewUrl\x18\v \x01(\tR\n" +
	"previewUrl\x12\"\n" +
	"\foriginalPath\x18\x0e \x01(\tR\foriginalPath\x12 \n" +
	"\visDirectory\x18\x1e \x01(\bR\visDirectory\x12\x16\n" +
	"\x06isRoot\x18\x1f \x01(\bR\x06isRoot\x12 \n" +
	"\visCloudRoot\x18  \x01(\bR\visCloudRoot\x12*\n" +
	"\x10isCloudDirectory\x18! \x01(\bR\x10isCloudDirectory\x12 \n" +
	"\visCloudFile\x18\" \x01(\bR\visCloudFile\x12&\n" +
	"\x0eisSearchResult\x18# \x01(\bR\x0eisSearchResult\x12 \n" +
	"\visForbidden\x18$ \x01(\bR\visForbidden\x12\x1c\n" +
	"\tcanSearch\x18? \x01(\bR\tcanSearch\x12.\n" +
	"\x12canOfflineDownload\x18B \x01(\bR\x12canOfflineDownload\".\n" +
	"\bFileType\x12\r\n" +
	"\tDirectory\x10\x00\x12\b\n" +
	"\x04File\x10\x01\x12\t\n" +
	"\x05Other\x10\x02\"}\n" +
	"\x13FileOperationResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage\x12(\n" +
	"\x0fresultFilePaths\x18\x03 \x03(\tR\x0fresultFilePaths\"\xd5\x02\n" +
	"\x0fCopyFileRequest\x12\"\n" +
	"\ftheFilePaths\x18\x01 \x03(\tR\ftheFilePaths\x12\x1a\n" +
	"\bdestPath\x18\x02 \x01(\tR\bdestPath\x12W\n" +
	"\x0econflictPolicy\x18\x03 \x01(\x0e2*.clouddrive.CopyFileRequest.ConflictPolicyH\x00R\x0econflictPolicy\x88\x01\x01\x12A\n" +
	"\x19handleConflictRecursively\x18\x05 \x01(\bH\x01R\x19handleConflictRecursively\x88\x01\x01\"5\n" +
	"\x0eConflictPolicy\x12\r\n" +
	"\tOverwrite\x10\x00\x12\n" +
	"\n" +
	"\x06Rename\x10\x01\x12\b\n" +
	"\x04Skip\x10\x02B\x11\n" +
	"\x0f_conflictPolicyB\x1c\n" +
	"\x1a_handleConflictRecursively\"\x99\x01\n" +
	"\x15AddOfflineFileRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\tR\x04urls\x12\x1a\n" +
	"\btoFolder\x18\x02 \x01(\tR\btoFolder\x127\n" +
	"\x14checkFolderAfterSecs\x18\x03 \x01(\x04H\x00R\x14checkFolderAfterSecs\x88\x01\x01B\x17\n" +
	"\x15_checkFolderAfterSecs\"\x98\x01\n" +
	"\x14AddSharedLinkRequest\x12$\n" +
	"\rsharedLinkUrl\x18\x01 \x01(\tR\rsharedLinkUrl\x12+\n" +
	"\x0esharedPassword\x18\x02 \x01(\tH\x00R\x0esharedPassword\x88\x01\x01\x12\x1a\n" +
	"\btoFolder\x18\x03 \x01(\tR\btoFolderB\x11\n" +
	"\x0f_sharedPassword\"\x8c\x01\n" +
	"\x19GetDownloadUrlPathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\apreview\x18\x02 \x01(\bR\apreview\x12\x1b\n" +
	"\tlazy_read\x18\x03 \x01(\bR\blazyRead\x12$\n" +
	"\x0eget_direct_url\x18\x04 \x01(\bR\fgetDirectUrl\"\xfe\x02\n" +
	"\x13DownloadUrlPathInfo\x12(\n" +
	"\x0fdownloadUrlPath\x18\x01 \x01(\tR\x0fdownloadUrlPath\x12!\n" +
	"\texpiresIn\x18\x02 \x01(\x04H\x00R\texpiresIn\x88\x01\x01\x12!\n" +
	"\tdirectUrl\x18\x03 \x01(\tH\x01R\tdirectUrl\x88\x01\x01\x12!\n" +
	"\tuserAgent\x18\x04 \x01(\tH\x02R\tuserAgent\x88\x01\x01\x12d\n" +
	"\x11additionalHeaders\x18\x05 \x03(\v26.clouddrive.DownloadUrlPathInfo.AdditionalHeadersEntryR\x11additionalHeaders\x1aD\n" +
	"\x16AdditionalHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_expiresInB\f\n" +
	"\n" +
	"_directUrlB\f\n" +
	"\n" +
	"_userAgent\"\xbd\x01\n" +
	"\tTokenInfo\x12\x18\n" +
	"\arootDir\x18\x02 \x01(\tR\arootDir\x12>\n" +
	"\vpermissions\x18\x03 \x01(\v2\x1c.clouddrive.TokenPermissionsR\vpermissions\x12\"\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x04H\x00R\texpiresIn\x88\x01\x01\x12#\n" +
	"\rfriendly_name\x18\x05 \x01(\tR\ffriendlyNameB\r\n" +
	"\v_expires_in\"\xbc\x02\n" +
	"\n" +
	"MountPoint\x12\x1e\n" +
	"\n" +
	"mountPoint\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x1c\n" +
	"\tsourceDir\x18\x02 \x01(\tR\tsourceDir\x12\x1e\n" +
	"\n" +
	"localMount\x18\x03 \x01(\bR\n" +
	"localMount\x12\x1a\n" +
	"\breadOnly\x18\x04 \x01(\bR\breadOnly\x12\x1c\n" +
	"\tautoMount\x18\x05 \x01(\bR\tautoMount\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\a \x01(\rR\x03gid\x12 \n" +
	"\vpermissions\x18\b \x01(\tR\vpermissions\x12\x1c\n" +
	"\tisMounted\x18\t \x01(\bR\tisMounted\x12\x1e\n" +
	"\n" +
	"failReason\x18\n" +
	" \x01(\tR\n" +
	"failReason\x12\x12\n" +
	"\x04name\x18\v \x01(\tR\x04name\"P\n" +
	"\x14GetMountPointsResult\x128\n" +
	"\vmountPoints\x18\x01 \x03(\v2\x16.clouddrive.MountPointR\vmountPoints2\xa2\x06\n" +
	"\x11CloudDriveFileSrv\x12K\n" +
	"\rGetSystemInfo\x12\x16.google.protobuf.Empty\x1a .clouddrive.CloudDriveSystemInfo\"\x00\x12?\n" +
	"\bGetToken\x12\x1b.clouddrive.GetTokenRequest\x1a\x14.clouddrive.JWTToken\"\x00\x12C\n" +
	"\x0fGetApiTokenInfo\x12\x17.clouddrive.StringValue\x1a\x15.clouddrive.TokenInfo\"\x00\x12L\n" +
	"\vGetSubFiles\x12\x1e.clouddrive.ListSubFileRequest\x1a\x19.clouddrive.SubFilesReply\"\x000\x01\x12L\n" +
	"\x10GetSearchResults\x12\x19.clouddrive.SearchRequest\x1a\x19.clouddrive.SubFilesReply\"\x000\x01\x12J\n" +
	"\bCopyFile\x12\x1b.clouddrive.CopyFileRequest\x1a\x1f.clouddrive.FileOperationResult\"\x00\x12W\n" +
	"\x0fAddOfflineFiles\x12!.clouddrive.AddOfflineFileRequest\x1a\x1f.clouddrive.FileOperationResult\"\x00\x12K\n" +
	"\rAddSharedLink\x12 .clouddrive.AddSharedLinkRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x0eGetMountPoints\x12\x16.google.protobuf.Empty\x1a .clouddrive.GetMountPointsResult\"\x00\x12^\n" +
	"\x12GetDownloadUrlPath\x12%.clouddrive.GetDownloadUrlPathRequest\x1a\x1f.clouddrive.DownloadUrlPathInfo\"\x00B;Z9bosstransfer/internal/adapters/clouddrive2/internal/pb;pbb\x06proto3"

var (
	file_clouddrive_proto_rawDescOnce sync.Once
	file_clouddrive_proto_rawDescData []byte
)

func file_clouddrive_proto_rawDescGZIP() []byte {
	file_clouddrive_proto_rawDescOnce.Do(func() {
		file_clouddrive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clouddrive_proto_rawDesc), len(file_clouddrive_proto_rawDesc)))
	})
	return file_clouddrive_proto_rawDescData
}

var file_clouddrive_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_clouddrive_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_clouddrive_proto_goTypes = []any{
	(CloudDriveFile_FileType)(0),        // 0: clouddrive.CloudDriveFile.FileType
	(CopyFileRequest_ConflictPolicy)(0), // 1: clouddrive.CopyFileRequest.ConflictPolicy
	(*GetTokenRequest)(nil),             // 2: clouddrive.GetTokenRequest
	(*JWTToken)(nil),                    // 3: clouddrive.JWTToken
	(*CloudDriveSystemInfo)(nil),        // 4: clouddrive.CloudDriveSystemInfo
	(*StringValue)(nil),                 // 5: clouddrive.StringValue
	(*TokenPermissions)(nil),            // 6: clouddrive.TokenPermissions
	(*ListSubFileRequest)(nil),          // 7: clouddrive.ListSubFileRequest
	(*SearchRequest)(nil),               // 8: clouddrive.SearchRequest
	(*SubFilesReply)(nil),               // 9: clouddrive.SubFilesReply
	(*CloudDriveFile)(nil),              // 10: clouddrive.CloudDriveFile
	(*FileOperationResult)(nil),         // 11: clouddrive.FileOperationResult
	(*CopyFileRequest)(nil),             // 12: clouddrive.CopyFileRequest
	(*AddOfflineFileRequest)(nil),       // 13: clouddrive.AddOfflineFileRequest
	(*AddSharedLinkRequest)(nil),        // 14: clouddrive.AddSharedLinkRequest
	(*GetDownloadUrlPathRequest)(nil),   // 15: clouddrive.GetDownloadUrlPathRequest
	(*DownloadUrlPathInfo)(nil),         // 16: clouddrive.DownloadUrlPathInfo
	(*TokenInfo)(nil),                   // 17: clouddrive.TokenInfo
	(*MountPoint)(nil),                  // 18: clouddrive.MountPoint
	(*GetMountPointsResult)(nil),        // 19: clouddrive.GetMountPointsResult
	nil,                                 // 20: clouddrive.DownloadUrlPathInfo.AdditionalHeadersEntry
	(*timestamppb.Timestamp)(nil),       // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 22: google.protobuf.Empty
}
var file_clouddrive_proto_depIdxs = []int32{
	21, // 0: clouddrive.JWTToken.expiration:type_name -> google.protobuf.Timestamp
	10, // 1: clouddrive.SubFilesReply.subFiles:type_name -> clouddrive.CloudDriveFile
	0,  // 2: clouddrive.CloudDriveFile.fileType:type_name -> clouddrive.CloudDriveFile.FileType
	21, // 3: clouddrive.CloudDriveFile.createTime:type_name -> google.protobuf.Timestamp
	21, // 4: clouddrive.CloudDriveFile.writeTime:type_name -> google.protobuf.Timestamp
	21, // 5: clouddrive.CloudDriveFile.accessTime:type_name -> google.protobuf.Timestamp
	1,  // 6: clouddrive.CopyFileRequest.conflictPolicy:type_name -> clouddrive.CopyFileRequest.ConflictPolicy
	20, // 7: clouddrive.DownloadUrlPathInfo.additionalHeaders:type_name -> clouddrive.DownloadUrlPathInfo.AdditionalHeadersEntry
	6,  // 8: clouddrive.TokenInfo.permissions:type_name -> clouddrive.TokenPermissions
	18, // 9: clouddrive.GetMountPointsResult.mountPoints:type_name -> clouddrive.MountPoint
	22, // 10: clouddrive.CloudDriveFileSrv.GetSystemInfo:input_type -> google.protobuf.Empty
	2,  // 11: clouddrive.CloudDriveFileSrv.GetToken:input_type -> clouddrive.GetTokenRequest
	5,  // 12: clouddrive.CloudDriveFileSrv.GetApiTokenInfo:input_type -> clouddrive.StringValue
	7,  // 13: clouddrive.CloudDriveFileSrv.GetSubFiles:input_type -> clouddrive.ListSubFileRequest
	8,  // 14: clouddrive.CloudDriveFileSrv.GetSearchResults:input_type -> clouddrive.SearchRequest
	12, // 15: clouddrive.CloudDriveFileSrv.CopyFile:input_type -> clouddrive.CopyFileRequest
	13, // 16: clouddrive.CloudDriveFileSrv.AddOfflineFiles:input_type -> clouddrive.AddOfflineFileRequest
	14, // 17: clouddrive.CloudDriveFileSrv.AddSharedLink:input_type -> clouddrive.AddSharedLinkRequest
	22, // 18: clouddrive.CloudDriveFileSrv.GetMountPoints:input_type -> google.protobuf.Empty
	15, // 19: clouddrive.CloudDriveFileSrv.GetDownloadUrlPath:input_type -> clouddrive.GetDownloadUrlPathRequest
	4,  // 20: clouddrive.CloudDriveFileSrv.GetSystemInfo:output_type -> clouddrive.CloudDriveSystemInfo
	3,  // 21: clouddrive.CloudDriveFileSrv.GetToken:output_type -> clouddrive.JWTToken
	17, // 22: clouddrive.CloudDriveFileSrv.GetApiTokenInfo:output_type -> clouddrive.TokenInfo
	9,  // 23: clouddrive.CloudDriveFileSrv.GetSubFiles:output_type -> clouddrive.SubFilesReply
	9,  // 24: clouddrive.CloudDriveFileSrv.GetSearchResults:output_type -> clouddrive.SubFilesReply
	11, // 25: clouddrive.CloudDriveFileSrv.CopyFile:output_type -> clouddrive.FileOperationResult
	11, // 26: clouddrive.CloudDriveFileSrv.AddOfflineFiles:output_type -> clouddrive.FileOperationResult
	22, // 27: clouddrive.CloudDriveFileSrv.AddSharedLink:output_type -> google.protobuf.Empty
	19, // 28: clouddrive.CloudDriveFileSrv.GetMountPoints:output_type -> clouddrive.GetMountPointsResult
	16, // 29: clouddrive.CloudDriveFileSrv.GetDownloadUrlPath:output_type -> clouddrive.DownloadUrlPathInfo
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_clouddrive_proto_init() }
func file_clouddrive_proto_init() {
	if File_clouddrive_proto != nil {
		return
	}
	file_clouddrive_proto_msgTypes[0].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[2].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[5].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[6].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[10].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[11].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[12].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[14].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clouddrive_proto_rawDesc), len(file_clouddrive_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clouddrive_proto_goTypes,
		DependencyIndexes: file_clouddrive_proto_depIdxs,
		EnumInfos:         file_clouddrive_proto_enumTypes,
		MessageInfos:      file_clouddrive_proto_msgTypes,
	}.Build()
	File_clouddrive_proto = out.File
	file_clouddrive_proto_goTypes = nil
	file_clouddrive_proto_depIdxs = nil
}
