// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: clouddrive.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudDriveFileSrv_GetSystemInfo_FullMethodName      = "/clouddrive.CloudDriveFileSrv/GetSystemInfo"
	CloudDriveFileSrv_GetToken_FullMethodName           = "/clouddrive.CloudDriveFileSrv/GetToken"
	CloudDriveFileSrv_GetApiTokenInfo_FullMethodName    = "/clouddrive.CloudDriveFileSrv/GetApiTokenInfo"
	CloudDriveFileSrv_GetSubFiles_FullMethodName        = "/clouddrive.CloudDriveFileSrv/GetSubFiles"
	CloudDriveFileSrv_GetSearchResults_FullMethodName   = "/clouddrive.CloudDriveFileSrv/GetSearchResults"
	CloudDriveFileSrv_CopyFile_FullMethodName           = "/clouddrive.CloudDriveFileSrv/CopyFile"
	CloudDriveFileSrv_AddOfflineFiles_FullMethodName    = "/clouddrive.CloudDriveFileSrv/AddOfflineFiles"
	CloudDriveFileSrv_AddSharedLink_FullMethodName      = "/clouddrive.CloudDriveFileSrv/AddSharedLink"
	CloudDriveFileSrv_GetMountPoints_FullMethodName     = "/clouddrive.CloudDriveFileSrv/GetMountPoints"
	CloudDriveFileSrv_GetDownloadUrlPath_FullMethodName = "/clouddrive.CloudDriveFileSrv/GetDownloadUrlPath"
)

// CloudDriveFileSrvClient is the client API for CloudDriveFileSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This is the smallest wire-compatible subset of the official CloudDrive2
// v1.0.17 proto needed by BossTransfer. Field numbers and RPC names must stay
// aligned with https://www.clouddrive2.com/api/clouddrive.proto.
type CloudDriveFileSrvClient interface {
	GetSystemInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CloudDriveSystemInfo, error)
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*JWTToken, error)
	GetApiTokenInfo(ctx context.Context, in *StringValue, opts ...grpc.CallOption) (*TokenInfo, error)
	GetSubFiles(ctx context.Context, in *ListSubFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubFilesReply], error)
	GetSearchResults(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubFilesReply], error)
	CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error)
	AddOfflineFiles(ctx context.Context, in *AddOfflineFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error)
	AddSharedLink(ctx context.Context, in *AddSharedLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetMountPoints(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMountPointsResult, error)
	GetDownloadUrlPath(ctx context.Context, in *GetDownloadUrlPathRequest, opts ...grpc.CallOption) (*DownloadUrlPathInfo, error)
}

type cloudDriveFileSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudDriveFileSrvClient(cc grpc.ClientConnInterface) CloudDriveFileSrvClient {
	return &cloudDriveFileSrvClient{cc}
}

func (c *cloudDriveFileSrvClient) GetSystemInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CloudDriveSystemInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudDriveSystemInfo)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*JWTToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JWTToken)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) GetApiTokenInfo(ctx context.Context, in *StringValue, opts ...grpc.CallOption) (*TokenInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenInfo)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_GetApiTokenInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) GetSubFiles(ctx context.Context, in *ListSubFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubFilesReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CloudDriveFileSrv_ServiceDesc.Streams[0], CloudDriveFileSrv_GetSubFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListSubFileRequest, SubFilesReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudDriveFileSrv_GetSubFilesClient = grpc.ServerStreamingClient[SubFilesReply]

func (c *cloudDriveFileSrvClient) GetSearchResults(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubFilesReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CloudDriveFileSrv_ServiceDesc.Streams[1], CloudDriveFileSrv_GetSearchResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, SubFilesReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudDriveFileSrv_GetSearchResultsClient = grpc.ServerStreamingClient[SubFilesReply]

func (c *cloudDriveFileSrvClient) CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileOperationResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_CopyFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) AddOfflineFiles(ctx context.Context, in *AddOfflineFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileOperationResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_AddOfflineFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) AddSharedLink(ctx context.Context, in *AddSharedLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_AddSharedLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) GetMountPoints(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMountPointsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMountPointsResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_GetMountPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) GetDownloadUrlPath(ctx context.Context, in *GetDownloadUrlPathRequest, opts ...grpc.CallOption) (*DownloadUrlPathInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadUrlPathInfo)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_GetDownloadUrlPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudDriveFileSrvServer is the server API for CloudDriveFileSrv service.
// All implementations must embed UnimplementedCloudDriveFileSrvServer
// for forward compatibility.
//
// This is the smallest wire-compatible subset of the official CloudDrive2
// v1.0.17 proto needed by BossTransfer. Field numbers and RPC names must stay
// aligned with https://www.clouddrive2.com/api/clouddrive.proto.
type CloudDriveFileSrvServer interface {
	GetSystemInfo(context.Context, *emptypb.Empty) (*CloudDriveSystemInfo, error)
	GetToken(context.Context, *GetTokenRequest) (*JWTToken, error)
	GetApiTokenInfo(context.Context, *StringValue) (*TokenInfo, error)
	GetSubFiles(*ListSubFileRequest, grpc.ServerStreamingServer[SubFilesReply]) error
	GetSearchResults(*SearchRequest, grpc.ServerStreamingServer[SubFilesReply]) error
	CopyFile(context.Context, *CopyFileRequest) (*FileOperationResult, error)
	AddOfflineFiles(context.Context, *AddOfflineFileRequest) (*FileOperationResult, error)
	AddSharedLink(context.Context, *AddSharedLinkRequest) (*emptypb.Empty, error)
	GetMountPoints(context.Context, *emptypb.Empty) (*GetMountPointsResult, error)
	GetDownloadUrlPath(context.Context, *GetDownloadUrlPathRequest) (*DownloadUrlPathInfo, error)
	mustEmbedUnimplementedCloudDriveFileSrvServer()
}

// UnimplementedCloudDriveFileSrvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudDriveFileSrvServer struct{}

func (UnimplementedCloudDriveFileSrvServer) GetSystemInfo(context.Context, *emptypb.Empty) (*CloudDriveSystemInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) GetToken(context.Context, *GetTokenRequest) (*JWTToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) GetApiTokenInfo(context.Context, *StringValue) (*TokenInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApiTokenInfo not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) GetSubFiles(*ListSubFileRequest, grpc.ServerStreamingServer[SubFilesReply]) error {
	return status.Errorf(codes.Unimplemented, "method GetSubFiles not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) GetSearchResults(*SearchRequest, grpc.ServerStreamingServer[SubFilesReply]) error {
	return status.Errorf(codes.Unimplemented, "method GetSearchResults not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) CopyFile(context.Context, *CopyFileRequest) (*FileOperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyFile not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) AddOfflineFiles(context.Context, *AddOfflineFileRequest) (*FileOperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOfflineFiles not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) AddSharedLink(context.Context, *AddSharedLinkRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSharedLink not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) GetMountPoints(context.Context, *emptypb.Empty) (*GetMountPointsResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMountPoints not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) GetDownloadUrlPath(context.Context, *GetDownloadUrlPathRequest) (*DownloadUrlPathInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDownloadUrlPath not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) mustEmbedUnimplementedCloudDriveFileSrvServer() {}
func (UnimplementedCloudDriveFileSrvServer) testEmbeddedByValue()                           {}

// UnsafeCloudDriveFileSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudDriveFileSrvServer will
// result in compilation errors.
type UnsafeCloudDriveFileSrvServer interface {
	mustEmbedUnimplementedCloudDriveFileSrvServer()
}

func RegisterCloudDriveFileSrvServer(s grpc.ServiceRegistrar, srv CloudDriveFileSrvServer) {
	// If the following call pancis, it indicates UnimplementedCloudDriveFileSrvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudDriveFileSrv_ServiceDesc, srv)
}

func _CloudDriveFileSrv_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).GetSystemInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_GetApiTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).GetApiTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_GetApiTokenInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).GetApiTokenInfo(ctx, req.(*StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_GetSubFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSubFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CloudDriveFileSrvServer).GetSubFiles(m, &grpc.GenericServerStream[ListSubFileRequest, SubFilesReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudDriveFileSrv_GetSubFilesServer = grpc.ServerStreamingServer[SubFilesReply]

func _CloudDriveFileSrv_GetSearchResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CloudDriveFileSrvServer).GetSearchResults(m, &grpc.GenericServerStream[SearchRequest, SubFilesReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudDriveFileSrv_GetSearchResultsServer = grpc.ServerStreamingServer[SubFilesReply]

func _CloudDriveFileSrv_CopyFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).CopyFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_CopyFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).CopyFile(ctx, req.(*CopyFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_AddOfflineFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOfflineFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).AddOfflineFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_AddOfflineFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).AddOfflineFiles(ctx, req.(*AddOfflineFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_AddSharedLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSharedLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).AddSharedLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_AddSharedLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).AddSharedLink(ctx, req.(*AddSharedLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_GetMountPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).GetMountPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_GetMountPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).GetMountPoints(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_GetDownloadUrlPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDownloadUrlPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).GetDownloadUrlPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_GetDownloadUrlPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).GetDownloadUrlPath(ctx, req.(*GetDownloadUrlPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudDriveFileSrv_ServiceDesc is the grpc.ServiceDesc for CloudDriveFileSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudDriveFileSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clouddrive.CloudDriveFileSrv",
	HandlerType: (*CloudDriveFileSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemInfo",
			Handler:    _CloudDriveFileSrv_GetSystemInfo_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _CloudDriveFileSrv_GetToken_Handler,
		},
		{
			MethodName: "GetApiTokenInfo",
			Handler:    _CloudDriveFileSrv_GetApiTokenInfo_Handler,
		},
		{
			MethodName: "CopyFile",
			Handler:    _CloudDriveFileSrv_CopyFile_Handler,
		},
		{
			MethodName: "AddOfflineFiles",
			Handler:    _CloudDriveFileSrv_AddOfflineFiles_Handler,
		},
		{
			MethodName: "AddSharedLink",
			Handler:    _CloudDriveFileSrv_AddSharedLink_Handler,
		},
		{
			MethodName: "GetMountPoints",
			Handler:    _CloudDriveFileSrv_GetMountPoints_Handler,
		},
		{
			MethodName: "GetDownloadUrlPath",
			Handler:    _CloudDriveFileSrv_GetDownloadUrlPath_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSubFiles",
			Handler:       _CloudDriveFileSrv_GetSubFiles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSearchResults",
			Handler:       _CloudDriveFileSrv_GetSearchResults_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clouddrive.proto",
}
